### ISSUE TITLE
need to finish locking down virtualbox version

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/vagrant_infrastructure#11]
to prevent encountering problems that show up in php composer in guest vms

https://github.com/composer/composer/issues/5814

**Comment by lo5an** [comment]
Digging around and found this commit where the MediaWiki vagrant box [is switched](https://phabricator.wikimedia.org/rMWVA5b6190c7cc3859096317e787e80fa52e2107515f) from one version of VirtualBox version detection to another.

The old way relies on external commands and looks like it might be a little brittle, but I don't grok Ruby and the Vagrant internals enough to know what's going on in the new way.

**Comment by jsnshrmn** [comment]
closed by commit f0d555a
